### ISSUE TITLE
Impossibile trovare il file log4jConfig.xml

### ISSUE THREAD

**Issue by rosemgo** [rosemgo/AsteOnLine#5]
Eseguendo Test Case con JUnit, emerge il seguente errore: java.io.FileNotFoundException: WebContent\WEB-INF\log4jConfig.xml (Impossibile trovare il percorso specificato).

**Comment by rosemgo** [comment]
Il problema è sicuramente relativo al percorso del file, è necessario utilizzare "il path relativo".

**Comment by marcobelf** [comment]
Si, è sufficiente utilizzare il path relativo dell'applicazione e non il path assoluto.

**Comment by rosemgo** [comment]
Ho deciso di utilizzare un file di properties per la configurazione del log4j, e quindi definire una classe ContextListener che implementa l'interfaccia ServletContextListener in modo tale da leggere la locazione del file di properties log4j una sola volta, all'avvio di Tomcat. In questo modo il log4j è inizializzato con il suddetto file di properties.
