### ISSUE TITLE
Permettere ad utente amministratore di visualizzare la lista degli utenti e delle inserzioni.

### ISSUE THREAD

**Issue by rosemgo** [rosemgo/AsteOnLine#59]
Realizzare un sistema di visualizzazione da parte di un amministratore di:
- Lista utenti registrati
- Lista utenti bannati
- Lista inserzioni

**Comment by rosemgo** [comment]
@marcobelf puoi fare una sola lista di utente registrati dove per ognuno indichi il proprio stato (se bannato o meno).

**Comment by marcobelf** [comment]
@rosemgo La lista degli utenti registrati mostra per ogni utente se è bannato o meno. Nella pagina jsp viene mostrata solo una lista.
