### ISSUE TITLE
Permettere all'utente amministratore di mettere il sito OFF-LINE e di abilitare/disabilitare un utente all'uso del sito.

### ISSUE THREAD

**Issue by marcobelf** [rosemgo/AsteOnLine#61]
Realizzare un sistema che permetta all'amministratore di modificare lo stato del sito (OFF-LINE / ON-LINE) e di abilitare/disabilitare un utente registrato all'uso delle funzionalità dell'applicazione.

**Comment by rosemgo** [comment]
creare una pgina jsp che mostri il sito in manutenzione
