### ISSUE TITLE
Permettere ad un utente amministratore di inserire categorie, produttori, prodotti e keyword.

### ISSUE THREAD

**Issue by marcobelf** [rosemgo/AsteOnLine#62]
Realizzare un sistema di inserimento di:
- Categorie
- Produttori
- Prodotti
- Keyword da associare ai prodotti

**Comment by rosemgo** [comment]
Nella fase di aggiunta di un prodotto, è necessario permettere all'utente amministratore di poter visualizzare i prodotti già presenti nel database e le keyword presenti nel database.
