### ISSUE TITLE
Permettere ad un utente amministratore di eliminare categorie, produttori, prodotti, keyword ed inserzioni.

### ISSUE THREAD

**Issue by marcobelf** [rosemgo/AsteOnLine#64]
Realizzare un sistema di eliminazione dal database di:
- Categorie
- Produttori
- Prodotti
- Keyword da associare ai prodotti
- Inserzioni

**Comment by rosemgo** [comment]
E' necessario mantenere l'integrità del database: eliminare una categoria è possibile solo se non ci sono prodotti, produttori ed inserzioni ad essa assegnati, quindi le eliminazioni vanno fatte a ritroso, partendo dalle inserzioni, poi i prodotti ecc.
