### ISSUE TITLE
Gestione della scadenze delle aste su ogni singola inserzione

### ISSUE THREAD

**Issue by rosemgo** [rosemgo/AsteOnLine#9]
E' necessario che lo stato di ogni inserzione venga aggiornato al momento della data di scadenza. Se l'inserzione non ha rivecuto offerte, lo stato risulta "scaduto", se vi è almeno un'offerta, lo stato deve essere "aggiudicata".
Come è possibile realizzare qualcosa che si preoccupi di fare ciò alla scadenza dell'asta?

**Comment by marcobelf** [comment]
Bisogna fare un controllo su ogni inserzione, per conoscere il momento della scadenza ed aggiornare lo stato.

**Comment by rosemgo** [comment]
In effetti avevo pensato ad un thread che partisse al momento dell'inserimento nel sistema dell'inserzione, per addormentarsi fino alla data di scadenza dell'asta. A quel punto, il thread dovrebbe svegliarsi ed aggiornare lo stato dell'asta in "aggiudicata" (assegnandola all'ultimo offerente), oppure in "scaduta".
Che ne pensi?

**Comment by marcobelf** [comment]
Esatto, proprio questo intendevo.

**Comment by marcobelf** [comment]
Pensandoci bene si verificherebbe un bug nel caso in cui il venditore modificasse l'inserzione mettendo una data di scadenza più imminente.

**Comment by rosemgo** [comment]
Si è vero. Allora quando il thread si risveglia, è necessario controllare se lo stato dell'inserzione è ancora in asta e se l'inserzione ha ancora la stessa data di scadenza. Nel caso la data di scadenza fosse stata modificata, il thread termina senza fare alcuna operazione.

**Comment by rosemgo** [comment]
Ho riaperto l'issue perchè in caso di aggiornamento della data di scadenza di un'inserzione da parte del venditore, è necessario far partire un nuovo thread che ne gestisca la scadenza! 
Questo va gestito nella Servlet adibita all'aggiornamento dell'inserzione.

**Comment by rosemgo** [comment]
Ogni volta che viene inserita un'inserzione parte un thread che al momento della scadenza dell'asta ne aggiorna lo stato. In caso di riavvio del web server, quindi verrebbero persi i thread avviati per ogni inserzione inserita, perciò all'avvio deve essere creato un Thread per inserzione che ne controlli la scadenza.
